# Generated by Django 3.0.2 on 2020-01-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='image',
            field=models.ImageField(default='image', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='image2', upload_to='avatar/'),
        ),
    ]
