# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-15 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200115_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile',
        ),
    ]
